### ISSUE TITLE
Proposal for new structure

### ISSUE THREAD

**Issue by hannob** [SecurityFail/kompromat#38]
I would like to make some proposals for the structure of the repo.

= Splitting out large collections =

Right now handling the repo is sometimes time consuming, as git does not work very well with very large collections of files, and also some filesystems aren't well equipped to handle very large directories.

I would propose to split some large collections into separate repositories. I would propose to have these repositories for now:
* Debian bug (debian_openssl_weak_keys directory)
* Malware/Ransomware keys (all *_malware directories)
* github.com/surespot
* phuctor.nosuchlabs.com
* Everything else

As a rule of thumb I'd propose to not have anything in the "Everything else" repostiroy with more than 10k keys. Furthermore for the very large collections (e.g. sleeper_malware alone has 120k keys) to have some splitup, as some filesystems really struggle to handle that large directories. Things like the sleeper_malware dir could be prefix-sorted (e.g. have a subdir for the first 2 characters of the filename, e.g. 11/111NAFjoKJXMNQ9hCAQnjB2huDPdDb1Fb.key).

I would also propose to have some basic sorting of the "Everything else" into categories, so we have a few upper directories that already give a good idea what's in there. Here's my proposal for categories (some of them are already existing directories):
* documentation
* firmware (e.g. littleblackbox, avm)
* localtls (e.g. Spotify, TorrentTime)
* mitm tls (e.g. komodia)
* rfc
* software
* testvectors
* misc (everything else)

**Comment by BenBE** [comment]
What set of keys are you refering to with `github.com/surespot`?

From a general point I'm okay with this structure. For the top repositories maybe split like this:

* Debian OpenSSL Bug
* Malware/Ransomware
* Key Material Attacks (e.g. phuctor.nosuchlabs.com, ROCA, …)
* Development (keys from source, documentation, tests, testvectors, and specs)
* Everything else (FW, MITM/Local TLS, Software, Manually reconstructed, …)

For really large key sets like phuctor.nosuchlabs.com we could even give them their own repo from the start.

Also it won't hurt to have a small utility repo with scripts/tools to check/repair/reconstruct/normalize keys.

**Comment by hannob** [comment]
github.com/surespot is a subdir in the src directory of the repo. It's 40k keys.

I think I'd prefer to keep most of the smaller things together, i.e. have your last 2 bulletpoints in one repo.

**Comment by BenBE** [comment]
Given that the Dev repo will contain mass collections like github, gitlab, so, … it's likely to grow to some quite decent size. But I'm more or less indifferent about having those two point in one or split them. My hunch is to split them.

**Comment by BenBE** [comment]
Okay, I'm right now creating some split repos for:

* Debian OpenSSL weak keys: https://github.com/SecurityFail/debian-openssl-weak-keys
* Malware/Ransomware decryption keys: https://github.com/SecurityFail/malware
* Key factorization results from the Phuctor project: https://github.com/SecurityFail/phuctor
* Surespot Messenger repository keys: https://github.com/SecurityFail/surespot

Splitting and uploading those repositories takes some time to complete.

**Comment by BenBE** [comment]
I think we're done with this for now. Closing.
